language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

script:
  - cargo test --all
  - rustup component add rustfmt
  - cargo fmt --all -- --check
  - cargo build --release

notifications:
  email: false
