[package]
name = "iso8601"
version = "0.1.0"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>", "Hendrik Sollich"]

description = "Parsing ISO8601 dates using nom"

homepage = "http://badboy.github.io/iso8601/"
repository = "https://github.com/badboy/iso8601"
documentation = "http://badboy.github.io/iso8601/"
license = "MIT"
readme = "README.md"


[dependencies]
nom = "0.5"

clippy = {version = "0.0.21", optional = true}

[features]
default = []
dev = ["clippy"]
